### ISSUE TITLE
Undefined property: pocketmine\network\mcpe\protocol\InventoryTransactionPacket::$actions" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/DataPacket

### ISSUE THREAD

**Issue by nghiaomg** [organization/TradeAPI#6] opened 2021-07-15 09:02 UTC
public function onDataPacketReceive(DataPacketReceiveEvent $event){
		if(($pk = $event->getPacket()) instanceof InventoryTransactionPacket){
			/** @var InventoryTransactionPacket $pk */
			$res = [];
			$c = false;
			foreach($pk->actions as $_ => $action){
				$after = $action;
				if($action->windowId === ContainerIds::UI && ($action->inventorySlot === 4 || $action->inventorySlot === 5 || $action->inventorySlot === 50)){
					if($action->inventorySlot === 50){
						if(TradeAPI::getInstance()->isTrading($event->getPlayer())){
							$action->inventorySlot = 51;
						}else{
							$res[] = $after;
							continue;
						}
					}

**Comment by nnnlog** [comment] 2021-07-15 10:29
Duplicate of #5

**Closed as completed by nnnlog** 2021-07-15 10:29 UTC
Labels: bug, duplicate
